import tkinter as tk
root = tk.Tk()
root.title("Método Grid")
root.geometry("250x140")
Frame1=tk.Frame(width=0,height=50)
Frame1.grid(row=0,column=0)
Titulo=tk.Label(root, text="Triage Covid-19")
Titulo.config(font=("Arial",20),fg="red",padx=10,pady=10)
Titulo.place(x=0, y=0)
LabelNombre= tk.Label(root, text="Nombre :")
LabelNombre.grid(row=1,column=1, padx=10, pady=5)
EntryNombre=tk.Entry(root)
EntryNombre.grid(row=1, column=2, padx=10,pady=5)
LabelApellido= tk.Label(root, text="Apellido :")
LabelApellido.grid(row=2,column=1, padx=10, pady=5)
EntryApellido=tk.Entry(root)
EntryApellido.grid(row=2, column=2, padx=10,pady=5)

root.mainloop()